name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CONAN_PRESET_NAME: conan-release
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Create default profile
      run: conan profile detect
            
    - name: Install dependencies
      run: conan install . --build=missing

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake --preset ${{env.CONAN_PRESET_NAME}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --preset ${{env.CONAN_PRESET_NAME}}

    - name: Run tests
      run: |
        ${{github.workspace}}/build/test_package
        ${{github.workspace}}/build/test_lexer
        ${{github.workspace}}/build/test_parser
        ${{github.workspace}}/build/test_codegen
        ${{github.workspace}}/build/test_compile_ir
        ${{github.workspace}}/build/test_type_system
        ${{github.workspace}}/build/test_filemanager
        ${{github.workspace}}/build/test_serialization
        ${{github.workspace}}/build/test_output
        ${{github.workspace}}/build/test_resolve
        ${{github.workspace}}/build/test_interpreter
        

